<a href="https://colab.research.google.com/github/Abiel252005/ECBD-OntiverosCalvarioAbiel/blob/main/Extraccion9B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

**Conjunto de datos**

In [ ]:
datos = {
    "usuario": ["Ana", "Luis", "Carlos", "Beto", "Gael", "Juan", "Diego", "Padro"],
    "edad": [25, 30, 35, 40, 45, 50, 55,21],
    "ciudad":["CDMX", "Monterrey", "Guasalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Madrid"],
    "compras_realizadas": [5, 10, 15,1,23,13,15,67],
    "activo":[True, False, True, True,True, False,True,False ],
    "fecha_registro": ["2026-01-10", "2026-02-15", "2026-03-20", "2026-04-25", "2026-05-30", "2026-06-05", "2026-07-10", "2026-08-15"]
}

In [ ]:
#COVERTIR A DATA FRAME
df=pd.DataFrame(datos)

In [ ]:
df

  usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0     Ana    25         CDMX                   5    True     2026-01-10
1    Luis    30    Monterrey                  10   False     2026-02-15
2  Carlos    35  Guasalajara                  15    True     2026-03-20
3    Beto    40       Puebla                   1    True     2026-04-25
4    Gael    45       Cancun                  23    True     2026-05-30
5    Juan    50       Merida                  13   False     2026-06-05
6   Diego    55      Tijuana                  15    True     2026-07-10
7   Padro    21       Madrid                  67   False     2026-08-15

In [ ]:
#Crear un dataFRame con 1,000,000 de registros
cantidad=1000000

In [ ]:
import random

In [ ]:
#Datos aleatorios
nombres = ["Ana", "Luis", "Carlos", "Beto", "Gael", "Juan", "Diego", "Padro"],
ciudades = ["CDMX", "Monterrey", "Guasalajara", "Puebla", "Cancun", "Merida", "Tijuana", "Madrid"],
categorias = ["Tecnologia0", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "comida"]

In [ ]:
dfMillon = pd.DataFrame({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18, 70) for _ in range(cantidad)],
    "salario" : [random.randint(20000, 100000) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "categoria" : [random.choice(categorias) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020, 2026) for _ in range(cantidad)]
})

In [ ]:
dfMillon.dtypes

nombre           object
edad              int64
salario           int64
activo             bool
categoria        object
ciudad           object
anio_registro     int64
dtype: object

In [ ]:
dfMillon.memory_usage(deep=True)

Index                  132
nombre           128000000
edad               8000000
salario            8000000
activo             1000000
categoria         56432102
ciudad           128000000
anio_registro      8000000
dtype: int64

In [ ]:
dfMillon.memory_usage(deep=True).sum() /1024**2

np.float64(321.8004550933838)