<a href="https://colab.research.google.com/github/Abiel252005/ECBD-OntiverosCalvarioAbiel/blob/main/Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
#Crear un dataFRame con 1,000,000 de registros
cantidad=1000000

In [3]:
import random

In [4]:
influencers = ["Fernanfloo", "Vegueta77", "Gael_Cordova", "Betito", "Amlo", "Donald Trump", "Quin_jon_hun", "Elonk Musk", "Vladimir Putin"]
tipos_post = ["Imagen", "Reel", "Video", "Carrusel"]

In [10]:
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers) for _ in range(cantidad)],
    "likes": [random.randint(1000, 575000) for _ in range(cantidad)],
    "comentarios": [random.randint(1000, 50000)for _ in range(cantidad)],
    "fecha": [random.randint(2020, 2026) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post) for _ in range(cantidad)]
})

In [11]:
df_instagram

          influencer   likes  comentarios  fecha tipo_post
0       Gael_Cordova  258521        21677   2022  Carrusel
1         Elonk Musk  305041        35968   2025     Video
2       Gael_Cordova  138033        43892   2020  Carrusel
3             Betito  557065        38678   2023    Imagen
4         Fernanfloo  491092        29194   2026      Reel
...              ...     ...          ...    ...       ...
999995     Vegueta77  372879        13262   2025      Reel
999996          Amlo  534408        35146   2025  Carrusel
999997    Fernanfloo  415961        39354   2020     Video
999998     Vegueta77  463749        49200   2024     Video
999999        Betito  109497         8283   2021     Video

[1000000 rows x 5 columns]

In [12]:
df_instagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha           int64
tipo_post      object
dtype: object

In [13]:
df_instagram.memory_usage(deep=True)

Index               132
influencer     58887242
likes           8000000
comentarios     8000000
fecha           8000000
tipo_post      54750917
dtype: int64

In [14]:
df_instagram.memory_usage(deep=True).sum() /1024**2

np.float64(131.2621030807495)